keys:
  - &deimos age1npfazzgfgqfehghc4wszgqjl337ghae0xv352jaxy092s9ewzglsfmkxu7
  - &horus age1dt24qetqhy2ng53fyj69yq9hg8rdsg4ep0lvvhdg69xw9v4l0asqj6xzkh
  - &hestia age1anhvzwlgkpe985jkk863v0p8tv6rrweeg7k6k6kfwz708j3tte5suvphdn
  - &pluto age1axcwgv9w5eu6vvx0p97pwnlnfhqcj773alsf2m9ufj2jth3xrppsaun2rp
creation_rules:
  - path_regex: hosts/deimos/secrets.yaml$
    key_groups:
    - age:
      - *deimos
  - path_regex: hosts/horus/secrets.yaml$
    key_groups:
    - age:
      - *horus
  - path_regex: hosts/hestia/secrets.yaml$
    key_groups:
    - age:
      - *hestia
  - path_regex: hosts/pluto/secrets.yaml$
    key_groups:
    - age:
      - *pluto
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
    - age:
      - *deimos
      - *horus
      - *hestia
      - *pluto
